name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 18 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-snake-animation
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: push snake.svg to the output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
