name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 18 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-snake-animation
    timeout-minutes: 5
    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
